name: Github Pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Build Publish
      run: |
        git clone https://github.com/JohnSundell/Publish.git
        cd Publish
        swift build -c release
        sudo install .build/release/publish-cli /usr/local/bin/publish

    - name: Generate Site
      run: publish generate

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./Output
        publish_branch: gh-pages
